name: Run checks

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["py36", "py37", "flake8", "mypy"]

        include:
          - environment: "py36"
            python: "3.6"
          - environment: "py37"
            python: "3.7"
          - environment: "flake8"
            python: "3.7"
          - environment: "mypy"
            python: "3.7"

    container:
      image: python:${{ matrix.python }}

    steps:
      - uses: actions/checkout@master
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tox
        run: |
          tox -e ${{ matrix.environment }}
