name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.6
      env:
        PYTHONDONTWRITEBYTECODE: TRUE
        PYTHONUNBUFFERED: TRUE

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: >-
          python -m pip install --upgrade --no-cache-dir
          pip wheel pep517 twine
      - name: Package project
        run: python -m pep517.build .
      - name: Upload distributions
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
